from typing import Self
from zoneinfo import ZoneInfo

import yaml
from loguru import logger
from pydantic import EmailStr, ValidationError
from pydantic_settings import BaseSettings

from reserve_it.models.field_types import YamlPath


class AppConfig(BaseSettings):
    """App configuration model passed to `build_app()`, either loaded from yaml file or
    constructed at runtime.

    Args:
        title (str): Title of your app, displayed on the home page if there are multiple
            resources, and openapi docs if enabled.
        description (str): Description of your app, displayed on the home page if there
            are multiple resources, and openapi docs if enabled.
        app_email (str): The email address of the dedicated Google account used for
            resource calendars.
        timezone (ZoneInfo): the IANA timezone to use for displaying all calendars.
        version (str): App version number.
        db_echo (bool): Whether resource sqlite databases should echo their operations
            to the console, for debugging purposes. Defaults to False.
        openapi_url (str | None, optional): If desired, a URL for the openapi docs
            generated by FastAPI. Defaults to None, which disables autogeneration of docs.
    """

    title: str
    description: str
    app_email: EmailStr
    timezone: ZoneInfo
    version: str
    db_echo: bool = False
    openapi_url: str | None = None

    @classmethod
    def from_yaml(cls, path: YamlPath) -> Self:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        return cls.model_validate_cleanly(data)

    @classmethod
    def model_validate_cleanly(cls, obj: dict, *, context=None, **kwargs):
        """model_validate overload that adds clean error log"""
        try:
            return super().model_validate(obj, context=context, **kwargs)
        except ValidationError as e:
            logger.error(f"Error loading AppConfig: {e}")
            # Kill the process cleanly; uvicorn will just see a non-zero exit
            raise SystemExit(1) from e
