from dataclasses import dataclass
from functools import partial

from devtools import pformat
from fastapi import APIRouter, Depends, FastAPI, Request
from fastapi.exceptions import RequestValidationError
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from pydantic import DirectoryPath, FilePath, ValidationError, validate_call
from rich import print

from reserve_it import SRC_ROOT, TEMPLATES
from reserve_it.app.calendar_service import GoogleCalendarService
from reserve_it.app.route_helpers import (
    bind_post_endpoint,
    cancel_reservation,
    get_form,
    submit_reservation,
)
from reserve_it.app.utils import (
    ResourceBundle,
    app_lifespan,
    get_all_resource_cfgs,
    handle_validation_error,
    init_dbs_and_bundles,
    init_gcal,
    load_resource_cfgs_from_yaml,
    log_request_validation_error,
    log_unexpected_exception,
)
from reserve_it.models.app_config import AppConfig
from reserve_it.models.reservation_request import ReservationRequest
from reserve_it.models.resource_config import CustomFormField, ResourceConfig


@dataclass
class AppDependencies:
    resource_bundles: dict[str, ResourceBundle]
    calendar_service: GoogleCalendarService

    def __post_init__(self):
        self.num_resources = len(self.resource_bundles)


@validate_call
def build_app(
    title: str,
    description: str,
    resource_config_path: DirectoryPath | FilePath,
    sqlite_db_path: DirectoryPath,
    gcal_cred_path: FilePath,
    gcal_token_path: FilePath | None = None,
    custom_form_fields: CustomFormField | list[CustomFormField] | None = None,
    request_classes: (
        type[ReservationRequest] | dict[str, type[ReservationRequest]]
    ) = ReservationRequest,
    version: str = "0.1.0",
    openapi_url: str | None = None,
) -> FastAPI:
    """Builds your resource reservation app using the resource yaml file(s) you defined.

    Args:
        title (str): Title of your app, displayed on the home page if there are multiple
            resources, and openapi docs if enabled.
        description (str): Description of your app, displayed on the home page if there
            are multiple resources, and openapi docs if enabled.
        resource_config_path (DirectoryPath | FilePath): Path to a single resource
            config yaml file, or a folder full of them.
        sqlite_db_path (DirectoryPath): Path to a folder where sqlite databases will be
            generated and stored. Each resource generates a database, and the reminder
            job scheduler generates an additional one that serves all resources.
        gcal_cred_path (FilePath): Path to the json file holding static OAuth client ID
            desktop app credentials you generated and downloaded from
            `https://console.cloud.google.com/apis/credentials`, `client_secret.json` or
            similarly named.
        gcal_token_path (FilePath | None, optional): If desired, path to a json file to
            save the refresh token and temporary auth token to on first authenticating
            your credentials, to reduce token churn. If passed, the token is automatically
            refreshed if expired. Defaults to None, in which case no tokens are saved.
        custom_form_fields (CustomFormField | list[CustomFormField] | None, optional):
            Custom html input form field(s) you want to add to all your resource
            reservation webpages. Note that custom form fields for individual resources
            should be defined in their respective yaml files. Defaults to None.
        request_classes (type[ReservationRequest] | dict[str, type[ReservationRequest]], optional):
            Either a single global ReservationRequest model subclass to use for form input
            validation for all resources, one a dict of one subclass per resource, with
            keys matching the names of the resource config files (minus any integer
            prefixes for ordering). Defaults to ReservationRequest, the default base
            model class.
        version (str, optional): App version number. Defaults to "0.1.0".
        openapi_url (str | None, optional): If desired, a URL for the openapi docs
            generated by FastAPI. Defaults to None, which disables autogeneration of docs.

    Returns:
        FastAPI: The FastAPI web app instance for your app.
    """
    app_cfg = AppConfig()
    dependencies = _initialize_dependencies(
        resource_config_path,
        custom_form_fields,
        request_classes,
        sqlite_db_path,
        app_cfg,
        gcal_cred_path,
        gcal_token_path,
    )

    app = _create_app(title, description, version, openapi_url, sqlite_db_path)
    _configure_app_state(app, app_cfg, dependencies)

    app.add_exception_handler(RequestValidationError, log_request_validation_error)
    app.add_exception_handler(ValidationError, handle_validation_error)
    app.add_exception_handler(Exception, log_unexpected_exception)

    # add js files
    app.mount("/static", StaticFiles(directory=SRC_ROOT / "static"), name="static")

    _register_resource_routes(app, dependencies.resource_bundles, app_cfg)

    # if there's only one resource, then no need for a separate home page
    if dependencies.num_resources > 1:
        _register_home_route(app, title, description)

    return app


def _initialize_dependencies(
    resource_config_path: DirectoryPath | FilePath,
    custom_form_fields: CustomFormField | list[CustomFormField] | None,
    request_classes: type[ReservationRequest] | dict[str, type[ReservationRequest]],
    sqlite_db_path: DirectoryPath,
    app_cfg: AppConfig,
    gcal_cred_path: FilePath,
    gcal_token_path: FilePath | None,
) -> AppDependencies:
    if isinstance(custom_form_fields, CustomFormField):
        custom_form_fields = [custom_form_fields]
    resource_configs = load_resource_cfgs_from_yaml(
        resource_config_path, custom_form_fields
    )
    if not resource_configs:
        raise ValueError(
            "you didn't create any resource config yaml files, or provided the wrong "
            "path for resource_config_path"
        )
    print(f"{pformat(resource_configs)}")

    normalized_requests = _normalize_request_classes(request_classes, resource_configs)
    resource_bundles = init_dbs_and_bundles(
        resource_configs, normalized_requests, sqlite_db_path, app_cfg.db_echo
    )
    gcal = init_gcal(app_cfg.timezone, gcal_cred_path, gcal_token_path)
    calendar_service = GoogleCalendarService(gcal)
    return AppDependencies(resource_bundles, calendar_service)


def _normalize_request_classes(
    request_classes: type[ReservationRequest] | dict[str, type[ReservationRequest]],
    resource_configs: dict[str, ResourceConfig],
) -> dict[str, type[ReservationRequest]]:
    if isinstance(request_classes, dict):
        if len(request_classes) != len(resource_configs):
            raise ValueError(
                "request_classes dict must be the same length as the number of resource configs."
            )
        missing = set(request_classes) - set(resource_configs)
        if missing:
            raise ValueError(
                "request_classes contains keys not present in resource_configs: "
                + ", ".join(sorted(missing))
            )
        return request_classes

    return {key: request_classes for key in resource_configs}


def _create_app(
    title: str,
    description: str,
    version: str,
    openapi_url: str | None,
    sqlite_db_path: DirectoryPath,
) -> FastAPI:
    return FastAPI(
        title=title,
        description=description,
        version=version,
        openapi_url=openapi_url,
        lifespan=partial(app_lifespan, sqlite_db_path=sqlite_db_path),
    )


def _configure_app_state(
    app: FastAPI, app_cfg: AppConfig, dependencies: AppDependencies
) -> None:
    app.state.config = app_cfg
    app.state.resource_bundles = dependencies.resource_bundles
    app.state.calendar_service = dependencies.calendar_service


def _register_resource_routes(
    app: FastAPI, resource_bundles: dict[str, ResourceBundle], app_cfg: AppConfig
) -> None:
    multi_resource = len(resource_bundles) > 1
    for bundle in resource_bundles.values():
        router: FastAPI | APIRouter
        if multi_resource:
            router = APIRouter(prefix=bundle.config.route_prefix)
        else:
            router = app
        build_route(router, bundle, app_cfg)
        if multi_resource:
            app.include_router(router)


def _register_home_route(app: FastAPI, title: str, description: str) -> None:
    @app.get("/", response_class=HTMLResponse)
    async def get_home_page(
        request: Request,
        all_configs: dict[str, ResourceConfig] = Depends(get_all_resource_cfgs),
    ):
        return TEMPLATES.TemplateResponse(
            "home.html",
            {
                "request": request,
                "site_title": title,
                "description": description,
                "resources": all_configs,
            },
        )


def build_route(
    router: FastAPI | APIRouter, bundle: ResourceBundle, app_cfg: AppConfig
):
    get_form_bound = partial(get_form, config=bundle.config)
    router.add_api_route(
        "/",
        endpoint=get_form_bound,
        name=f"get_form_{bundle.config.file_prefix}",
        methods=["GET"],
        response_class=HTMLResponse,
    )

    submit_bound = bind_post_endpoint(submit_reservation, bundle, app_cfg)
    router.add_api_route(
        "/reserve",
        endpoint=submit_bound,
        name=f"submit_{bundle.config.file_prefix}",
        methods=["POST"],
        response_class=HTMLResponse,
    )

    cancel_bound = bind_post_endpoint(cancel_reservation, bundle, app_cfg)
    router.add_api_route(
        "/cancel",
        endpoint=cancel_bound,
        name=f"cancel_{bundle.config.file_prefix}",
        methods=["POST"],
        response_class=HTMLResponse,
    )
